# azure-pipelines.yml
trigger:
- trunk  # Change this to your default branch

pool:
  vmImage: 'windows-latest'  # Use a Windows VM for .NET builds

variables:
  buildConfiguration: 'Release'  # Set the build configuration

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(3446f95d-1c75-4b4e-8ff8-11a5ca24f1c5)'
    command: 'build'
    projects: 'src/LaMa.Via.Auctus.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.tests.csproj'